### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by ncallister** [ascom-au/java-role#1]
Following the release procedure here: http://192.168.1.5/iwsoftware/wiki/Processes/Release/AnsibleRoles

- [x] Ensure that there is an issue for the release in the release milestone in order to track any changes required
- [x] Ensure that all issues assigned to the release milestone have been closed (except for the release issue)
- [x] Ensure that all issues that have resulted in commits have been closed (you will need to dig through the commit messages because many of the issues will belong to playbook projects)
- [x] Ensure that all issue specific branches have been merged and removed 

- [x] Create a tag for the release version
- [ ] Close the release issue
- [x] Close the milestone
- [x] Create a milestone for the next release by creating the issue to release the next version 
- [x] Create a new 1.0 branch for future development

**Comment by serg89** [comment]
Checked the status of the tickets un-ticked in the above list:

ascom-au/ensureconnect-playbook#1
The java role and other changes have been reviewed/qa'd and the ticket closed but the ticket was re-opened to include forgotten submodule updates. Module updates for the ensureconnect-playbook have no bearing on the java role so this ticket can be ticked off the list.

**Comment by serg89** [comment]
Checking the following projects for branch merges/removal.

ascom-au/install-iso#3 - branch merging/removal completed.
ascom-au/keepalived-role#1
ascom-au/durasuite-playbook#2
ascom-au/ensureconnect-playbook#1 - branch merging/removal completed.
https://119.9.13.178/iwsoftware/ticket/5507 - branch merging/removal completed.
https://119.9.13.178/iwsoftware/ticket/5504 - branch merging/removal completed.

**Comment by serg89** [comment]
Created the release_1.0 tag, https://github.com/ascom-au/java-role/releases/tag/release_1.0

**Comment by serg89** [comment]
Created the following milestones:

v1.0.1
v1.1

See https://github.com/ascom-au/ava-role/milestones

**Comment by serg89** [comment]
Created issues for the v1.0.1 and v1.1 releases:

v1.0.1 #2
v1.1 #3

**Comment by serg89** [comment]
Created new branch https://github.com/ascom-au/java-role/tree/branch_1.0

**Comment by ncallister** [comment]
Looks good. Good work!
No QA required for this.
